import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import products from "./../products.json";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to My Store</h1>

        <ul className={styles.grid}>
          {products.map((p) => {
            return (
              <li className={styles.card}>
                <img src={p.image} alt={p.title} />
                <a href="https://nextjs.org/docs">
                  <h2>{p.title}</h2>
                  <p>{p.price} ₹</p>
                  <p>{p.description}</p>
                </a>
              </li>
            );
          })}
        </ul>
      </main>
    </div>
  );
}
